M48
; DRILL file {KiCad (6.0.5)} date Tue Jan 23 17:13:28 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-23T17:13:28+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X92.88Y-106.1
X92.88Y-111.88
X92.895Y-119.8
X92.895Y-125.58
T0
M30
